# Markdown linting configuration
MD013: false  # Line length
MD033: false  # Inline HTML
MD041: false  # First line in file should be a top level header
MD022: false  # Headings should be surrounded by blank lines
MD032: false  # Lists should be surrounded by blank lines
MD009: false  # Trailing spaces
